receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://*
            - https://*

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
  transform:
    error_mode: ignore
    metric_statements:
      - context: metric
        statements:
         - set(description, "Duration of HTTP server requests.") where name == "http.server.duration"
         - set(description, "Number of active HTTP server requests.") where name == "http.server.active_requests"

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    # send_timestamps: true
    namespace: pulp
  logging:
    verbosity: detailed
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: []
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [transform, batch, memory_limiter]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]
