---
version: "3.7"

services:

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      # COLLECTOR_OTLP_ENABLED: "true"
      JAEGER_DISABLED: "true"
    ports:
      - "16686:16686"
      - "14250"
      - "14268"
      - "4317"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector
    command: [--config=/etc/otel-collector/otel-collector-config.yaml]
    volumes:
      - "{OCI_ENV_DIR}/profiles/{COMPOSE_PROFILE}/otel-collector:/etc/otel-collector"
    ports:
      - "1888"   # pprof extension
      - "8888"   # Prometheus metrics exposed by the collector
      - "8889"   # Prometheus exporter metrics
      - "13133" # health_check extension
      - "4318"   # OTLP http receiver
      - "55679" # zpages extension
    depends_on:
      - prometheus
      - jaeger

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - "{OCI_ENV_DIR}/profiles/{COMPOSE_PROFILE}/prometheus:/etc/prometheus"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    restart: "always"
    volumes:
      - "{OCI_ENV_DIR}/profiles/{COMPOSE_PROFILE}/grafana/provisioning:/etc/grafana/provisioning"
      - "{OCI_ENV_DIR}/profiles/{COMPOSE_PROFILE}/grafana/dashboards:/var/lib/grafana/dashboards"
      - "{OCI_ENV_DIR}/profiles/{COMPOSE_PROFILE}/grafana/config.ini:/etc/grafana/config.ini"
      # - type: bind
      #   source: ./grafana/config.ini
      #   target: /etc/grafana/config.ini
    ports:
      - "3000:3000"

networks:
  default:
    name: oci_env_default
    external: "true"
